### ISSUE TITLE
Shared library build

### ISSUE THREAD

**Issue by dmitchell** [snowflakedb/libsnowflakeclient#164]
I tried adding the ability to build a SHARED library exporting the signatures in client.h but it fails due to the included libraries being static. Is this a stupid idea? any idea how to get this to work?

**Comment by notkriswagner** [comment]
Hi @dmitchell ,

It is possible to get this to work but you would have to do a few things which may be undesirable. 

1. The following dependencies need to be installed: openssl, curl, aws-cpp-sdk, azure-sdk-lite, zlib and uuid.
2. You would need to install our version of curl since we have modified the library to do a stricter OCSP check. Using the standard version of curl would fail to work.
3. Modify the CMakeLists.txt file to build the library in a SHARED mode.

Option 2 is the one which you may find to be undesirable, but if you're okay with installing our version of curl system-wide then this should work for you
